---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-cm
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  my-cluster.cnf: |
    [mysqld]
    log-bin=mysql-bin
    server-id=0
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    [mysql]
    default-character-set=utf8mb4
    [client]
    default-character-set=utf8mb4
    [galera]
    binlog_format=ROW
    default_storage_engine=InnoDB
    innodb_autoinc_lock_mode=2
    bind-address=0.0.0.0
    wsrep-sst-method=rsync
  init.sh: |
    #!/bin/sh

    if [ ! -f "/etc/mysql/conf.d/mysql.cnf" ];then
      cp -f /etc/mysql/conf.d/mysql.cnf.j2 /etc/mysql/conf.d/mysql.cnf
      server_id=$(hostname | awk -F "-" '{print $NF;}')
      sed -i "s/server-id=0/server-id=${server_id}/g" /etc/mysql/conf.d/mysql.cnf
      mkdir -p /docker-entrypoint-initdb.d
      echo "server_id: $server_id"
      if [ $server_id -eq 0 ]; then # master
        touch /docker-entrypoint-initdb.d/master.sql
        {
          echo "CREATE USER \"$MYSQL_REPLICATION_USER\"@\"%\" IDENTIFIED BY \"$MYSQL_REPLICATION_PASSWORD\" PASSWORD EXPIRE NEVER ;"
          echo "ALTER  USER \"$MYSQL_REPLICATION_USER\"@\"%\" IDENTIFIED WITH mysql_native_password BY \"$MYSQL_REPLICATION_PASSWORD\";"
          echo "GRANT REPLICATION SLAVE ON *.* TO \"$MYSQL_REPLICATION_USER\"@\"%\" IDENTIFIED BY \"$MYSQL_REPLICATION_PASSWORD\" ;"
          echo "FLUSH PRIVILEGES ;"
        } > /docker-entrypoint-initdb.d/master.sql
      else # slave
        touch /docker-entrypoint-initdb.d/slave.sql
        {
          echo "STOP SLAVE;"
          echo "CHANGE MASTER TO master_host=\"$MYSQL_MASTER_SERVICE_HOST\", master_user=\"$MYSQL_REPLICATION_USER\", master_password=\"$MYSQL_REPLICATION_PASSWORD\" ;"
          echo "START SLAVE;"
        } > /docker-entrypoint-initdb.d/slave.sql
      fi
    fi