{{- $fullname := include "mysql.fullname" . -}}
{{- range $i, $e := until (int .Values.replicaCount) }}
#
---
apiVersion: v1
kind: Service
metadata:
  name: {{ print $fullname "-" (tuple $i | include "mysql.fnServiceName") }}
  labels:
    {{- include "mysql.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    statefulset.kubernetes.io/pod-name: mysql-{{ print (add $i 1) }}
    {{- include "mysql.selectorLabels" $ | nindent 4 }}
---
{{- end }}
