version: "3"

#volumes:
#  hostdir:
#    driver: local

services:
  artemis:
    image: vromero/activemq-artemis:2.16.0-alpine
    container_name: activemq-artemis
    restart: always
    ports:
      - "8161:8161"
      - "21616:61616"
      - "21613:61613"
      - "1199:1199"
      - "1198:1198"
    environment:
      - ENABLE_JMX=true
      - JMX_PORT=1199
      - JMX_RMI_PORT=1198
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=admin1234
    hostname: artemis
    # user: root

# docker-compose -f ./docker-compose-h2-standalone.yml up -d
