---
version: "3.3"
services:
  db:
    image: mysql
    container_name: mysql-svc
    ports:
      - "3307:3306"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --init-file=/sql/ddl/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - my-bridge
    volumes:
      - /tmp/data/mysql:/var/lib/mysql
      - ./init.sql:/sql/ddl/init.sql

networks:
  my-bridge:
    driver: bridge

# docker-compose -f ./docker-compose-mysql-standalone.yml up -d
