{{- $fullname := (include "kafka.fullname" .)  -}}
{{- $storage := .Values.volume.storage -}}
{{- $storageClassName := include "kafka.storageClassName" . -}}
{{- $pvLabels := (include "kafka.pvLabels" .) -}}
{{- range $i, $e := until (int .Values.replicaCount) }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-%d-pv" $fullname $i }}
  labels:
    {{- $pvLabels | nindent 4 }}
spec:
  capacity:
    storage: {{ $.Values.volume.storage }}
  storageClassName: {{ $storageClassName }}
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/kafka/{{ $i }}
    type: DirectoryOrCreate
  {{- with $.Values.nodeAffinity }}
  nodeAffinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{- end}}