apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-svc
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: broker
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
    - name: broker2
      port: {{ .Values.service.broker2.port }}
      targetPort: {{ .Values.service.broker2.targetPort }}
      protocol: TCP
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
