# version: "3" # 파일 규격 버전
# services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
#   db: shoppingmall# 서비스 명
#     image: mysql/latest # 사용할 이미지
#     container_name: jmlim-mysql # 컨테이너 이름 설정
#     ports:
#       - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
#     environment: # -e 옵션
#       MYSQL_ROOT_PASSWORD: "password"  # MYSQL 패스워드 설정 옵션
#     command: # 명령어 실행
#       - --character-set-server=utf8mb4
#       - --collation-server=utf8mb4_unicode_ci
#     volumes:
#       - /Users/jmlim/datadir:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
# 컨테이너 실행
# docker-compose 파일이 위치한 경로에서 아래 명령 실행
# docker-compose -f ./docker-compose.yml up -d
---
version: '3.0'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
    command: redis-server --requirepass admin1234 --appendonly yes
    restart: always

# docker-compose -f ./docker-compose-redis-standalone.yml up -d
