---
version: '3.0'

services:
  redis:
    image: "redis:latest"
    container_name: redis-svc
    command: redis-server --requirepass admin1234 --appendonly yes
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - my-bridge
    restart: always

networks:
  my-bridge:
    driver: bridge
# docker-compose -f ./docker-compose-redis-standalone.yml up -d
